version: 2
jobs:
  build:
    docker:
      - image: regentmarkets/debian-ci:stable
        user: nobody
        auth:
          username: circle4regentmarkets
          password: $DOCKERHUB_PASSWORD
    shell: /bin/bash -leo pipefail
    working_directory: /home/git/regentmarkets/perl-Finance-Underlying
    steps:
      - add_ssh_keys:
          fingerprints:
            - "85:5e:13:f8:60:b2:55:a1:df:d1:8e:77:17:4c:3b:2d"
      - run:
          name: Update git repositories
          command: /opt/circle/prepare-test.sh
      - run:
          name: Run test
          command: |
            source /etc/profile.d/perl5.sh
            dzil test
workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
          context: perl
